CREATE DATABASE QLSV3

USE QLSV3
GO

-- CREATE TABLE
CREATE TABLE KHOA (
	MAKHOA NVARCHAR(10) PRIMARY KEY NOT NULL,
	TENKHOA NVARCHAR(20) NOT NULL
)
GO 
CREATE TABLE LOP (
	MALOP NVARCHAR(10) PRIMARY KEY NOT NULL,
	TENLOP NVARCHAR(20) NOT NULL,
	SISO INT NOT NULL DEFAULT (0),
	MAKHOA NVARCHAR(10),
	FOREIGN KEY (MAKHOA) REFERENCES DBO.KHOA(MAKHOA)
)
GO 
CREATE TABLE SINHVIEN (
	MASV NVARCHAR(10) PRIMARY KEY,
	HOTEN NVARCHAR(30) NOT NULL,
	NGAYSINH DATETIME,
	GIOITINH BIT,
	MALOP NVARCHAR(10),
	FOREIGN KEY (MALOP) REFERENCES dbo.LOP
)

-- INSERT DATA
GO
INSERT INTO KHOA VALUES 
(	'K01',	'CNTT'	),
(	'K02',	N'Du lịch')
GO 
INSERT INTO LOP VALUES
(	'L03',	'CNTT3',	66,	'K01'	),
(	'L02',	N'Du lịch 1',	70,	'K02'	)
GO
INSERT INTO SINHVIEN VALUES
(	'SV01',	N'Nguyễn Việt Trung',	'20010930',	1,	'L03'	),
(	'SV02',	N'Nguyễn Văn A',	'20000101',	1,	'L02'	),
(	'SV03',	N'Nguyễn Thị Tý',	'20010101',	0,	'L02'	),
(	'SV04',	N'Nguyễn Văn Tèo',	'20010101', 1,	'L02'	),
(	'SV05',	N'Dương Thị Nở',	'20011010',	0,	'L02'	),
(	'SV06',	N'Dương Văn B',	'20011010',	1,	'L03'	),
(	'SV07',	N'Dương Thị C',	'20011010',	0,	'L02'	)

GO
/*DISPLAY
SELECT * FROM dbo.KHOA
SELECT * FROM dbo.LOP
SELECT * FROM dbo.SINHVIEN
*/

GO 
--- Câu 2
CREATE  VIEW viewLop 
AS 
	SELECT TENKHOA, COUNT(*) AS N'Số lớp'
	FROM dbo.LOP INNER JOIN dbo.KHOA ON KHOA.MAKHOA = LOP.MAKHOA
	GROUP BY TENKHOA

GO 
DROP VIEW dbo.viewLop
GO 
SELECT * FROM dbo.viewLop

GO 
-- Câu 3
CREATE FUNCTION fn_ThongTinSV ( @maKhoa NVARCHAR(10) )
RETURNS @bang TABLE (
	MASV NVARCHAR(10),
	HOTEN NVARCHAR(20),
	NGAYSINH DATETIME,
	GIOITINH NVARCHAR(10),
	TENLOP NVARCHAR(20),
	TENKHOA NVARCHAR(20)
)
AS 
	BEGIN 
		INSERT INTO @bang 
		SELECT MASV, HOTEN, NGAYSINH, CASE WHEN GIOITINH = 1 THEN 'Nam' WHEN GIOITINH = 0 THEN 'Nữ' END, TENLOP, TENKHOA
		FROM dbo.SINHVIEN	INNER JOIN dbo.LOP ON LOP.MALOP = SINHVIEN.MALOP
							INNER JOIN dbo.KHOA ON KHOA.MAKHOA = LOP.MAKHOA
		WHERE KHOA.MAKHOA = @maKhoa
		RETURN
	END

GO
DROP FUNCTION dbo.fn_ThongTinSV
SELECT * FROM dbo.fn_ThongTinSV( 'K02')

-- Câu 4
GO 
CREATE PROC sp_TimSVtheoTuoivaLop (@x INT, @y INT, @tenlop NVARCHAR(20) )
AS
	BEGIN
		IF ( NOT EXISTS ( SELECT * FROM dbo.SINHVIEN INNER JOIN dbo.LOP ON LOP.MALOP = SINHVIEN.MALOP
							INNER	JOIN dbo.KHOA ON KHOA.MAKHOA = LOP.MAKHOA
							WHERE TENLOP = @tenlop AND YEAR(GETDATE()) - YEAR(NGAYSINH) BETWEEN @x AND @y ))
			PRINT 'Khong co DL'
		ELSE
			BEGIN
				SELECT MASV, HOTEN, NGAYSINH, TENLOP, TENKHOA, YEAR(GETDATE()) - YEAR(NGAYSINH) AS 'Tuoi'
				FROM dbo.SINHVIEN	INNER JOIN dbo.LOP ON LOP.MALOP = SINHVIEN.MALOP
									INNER JOIN dbo.KHOA ON KHOA.MAKHOA = LOP.MAKHOA
				WHERE TENLOP = @tenlop AND YEAR(GETDATE()) - YEAR(NGAYSINH) BETWEEN @x AND @y 
			END
    END
GO 
EXEC dbo.sp_TimSVtheoTuoivaLop  20,   21,  N'1' 

--Câu 5
GO
CREATE FUNCTION fn_HienThiSV ( @tenKhoa NVARCHAR(20) )
RETURNS @bang TABLE (
	MASV NVARCHAR(10),
	HOTEN NVARCHAR(30),
	tuoi INT
)
AS 
	BEGIN
		INSERT INTO @bang 
		SELECT MASV, HOTEN, YEAR(GETDATE()) - YEAR(NGAYSINH) AS 'Tuoi'
		FROM dbo.SINHVIEN	INNER JOIN dbo.LOP ON LOP.MALOP = SINHVIEN.MALOP
							INNER JOIN dbo.KHOA ON KHOA.MAKHOA = LOP.MAKHOA
		WHERE TENKHOA = @tenKhoa
		RETURN
	END
GO 
SELECT * FROM dbo.fn_HienThiSV( N'CNTT' )