
USE QLSV
GO 


CREATE FUNCTION dbo.TINHDIEMTB ()
RETURNS TABLE
AS
	RETURN SELECT dbo.KQ.masv, SUM(dbo.KQ.diem*sotc)/SUM(sotc) AS DTB
	FROM dbo.monhoc, dbo.KQ
	WHERE dbo.monhoc.MaMH = dbo.KQ.MaMH
	GROUP BY dbo.KQ.masv;

GO
SELECT * FROM dbo.KQ
SELECT * FROM dbo.TINHDIEMTB()

GO

CREATE FUNCTION THONGKEMON( @TEN NVARCHAR(10))
RETURNS INT
AS
	BEGIN
		DECLARE @SOMON INT
		SELECT @SOMON = COUNT(*) FROM dbo.KQ INNER JOIN dbo.SINHVIEN ON SINHVIEN.masv = KQ.masv
		WHERE ten = @TEN
		RETURN @SOMON
	END

GO
SEL
SELECT dbo.THONGKEMON('HÀ')